### ISSUE TITLE
Character entity

### ISSUE THREAD

**Issue by jim-rosales** [zhikyang/colmar-academy#2]
When adding symbols such as the ampersand symbol to a site, it is best practice to add them via their [entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity). 

For example, we'd include `&` by using `&amp;`

https://github.com/zhikyang/colmar-academy/blob/51515778d80b0103a4e49119012dbfa357d3c036/index.html#L72

**Comment by zhikyang** [comment]
thanks!
