### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [zhikyang/colmar-academy#5]
Grade: Exceeds Expectations

Summary: 
Congrats on finishing you capstone project! Overall you did an excellent job syntactically as I only saw one issue in your entire project. Apart from this, your code was also straightforward to read considering you did an excellent job commenting all your files. 

To expand on your project as a challenge see if you can incorporate [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) in your CSS file. They seem like a great way to increase maintainability of your code while making everything slightly more readable.

**Comment by zhikyang** [comment]
indeed, variables seem to be a great way to manage repetitive items
